import type { EmailDef } from "./types";

export function emailDefs(): EmailDef[] {
  return [
    {
      id: "verify",
      audience: "Respondent",
      name: "Verify your email",
      subject: "Your Prodi-Surveys verification code",
      from: "Prodi-Surveys <no-reply@prodigitality.net>",
      to: "respondent",
      preheader: "Enter this code to verify your email and continue.",
      accent: "#4F46E5",
      vars: { code: "418 902" },
      blocks: [
        { type: "h", text: "Verify your email address" },
        { type: "p", text: "Thanks for registering for the Prodigitality baseline survey. Enter the code below to verify your email and continue to your survey." },
        { type: "code", text: "{{code}}" },
        { type: "note", text: "This code expires in 15 minutes. If you didn't request it, you can safely ignore this email." },
      ],
    },
    {
      id: "invite",
      audience: "Respondent",
      name: "Survey invitation",
      subject: "You're invited to the Prodigitality baseline survey",
      from: "Prodi-Surveys <no-reply@prodigitality.net>",
      to: "respondent",
      preheader: "Takes about 5–10 minutes to complete.",
      accent: "#E0195F",
      vars: { firstName: "Maria", surveyLink: "prodigitalitydata.live/s/INVITE-7F3K" },
      blocks: [
        { type: "h", text: "You've been invited to take part" },
        { type: "p", text: "Hi {{firstName}}, you've been invited to participate in a baseline data collection study for food processing businesses and partners. The survey takes about 5–10 minutes." },
        { type: "btn", text: "Start the survey" },
        { type: "p", text: "Or paste this link into your browser:" },
        { type: "linkbox", text: "{{surveyLink}}" },
        { type: "note", text: "Your responses help shape support programs for businesses like yours." },
      ],
    },
    {
      id: "verified",
      audience: "Respondent",
      name: "You're verified",
      subject: "Thank you for participating in the survey ✓",
      from: "Prodi-Surveys <no-reply@prodigitality.net>",
      to: "respondent",
      preheader: "Thank you for participating in the survey.",
      accent: "#15803D",
      vars: { firstName: "Maria" },
      blocks: [
        { type: "h", text: "Thank you for participating in the survey 🎉" },
        { type: "p", text: "Thank you, {{firstName}}. We've received your submission. Your participation in the Prodigitality baseline survey is complete." },
        { type: "note", text: "Thank you for taking the time to contribute to the study." },
      ],
    },
    {
      id: "rejected",
      audience: "Respondent",
      name: "Submission not approved",
      subject: "Update on your survey submission",
      from: "Prodi-Surveys <no-reply@prodigitality.net>",
      to: "respondent",
      preheader: "Your submission could not be verified.",
      accent: "#B91C1C",
      vars: {},
      blocks: [
        { type: "h", text: "Your submission could not be verified" },
        { type: "p", text: "Thank you for your interest in the study. After review, we were unable to verify your submission." },
        { type: "p", text: "If you believe this was a mistake, you may reply to this email and our team will take another look." },
      ],
    },
    {
      id: "paid",
      audience: "Enumerator",
      name: "Survey payout sent",
      subject: "Your survey payout has been sent",
      from: "Prodi-Surveys <no-reply@prodigitality.net>",
      to: "enumerator",
      preheader: "Your enumerator payout has been released.",
      accent: "#15803D",
      vars: { firstName: "Maria", amount: "₱400", surveys: "1", payoutMethod: "GCash •••• 412", dateSent: "Jun 20, 2026" },
      blocks: [
        { type: "h", text: "Your survey payout is on its way 💸" },
        { type: "p", text: "Hi {{firstName}}, payout for your verified survey(s) has been released to your registered payout account." },
        { type: "kv", rows: [["Amount", "{{amount}}"], ["Verified surveys", "{{surveys}}"], ["Method", "{{payoutMethod}}"], ["Date sent", "{{dateSent}}"]] },
        { type: "note", text: "Please allow 1–3 business days for the amount to reflect. ₱400 is paid per verified survey." },
      ],
    },
    {
      id: "paid-tumbler",
      audience: "Respondent",
      name: "Token sent — small token",
      subject: "Your small token is on its way",
      from: "Prodi-Surveys <no-reply@prodigitality.net>",
      to: "respondent",
      preheader: "Your small token is on its way.",
      accent: "#15803D",
      vars: { item: "Small token", shippedTo: "Juan Dela Cruz", estDelivery: "7–14 business days" },
      blocks: [
        { type: "h", text: "Your small token is on its way 🎁" },
        { type: "p", text: "Good news — your small token has been processed. Thank you for participating in the Prodigitality baseline survey." },
        { type: "kv", rows: [["Item", "{{item}}"], ["Recipient", "{{shippedTo}}"], ["Est. delivery", "{{estDelivery}}"]] },
        { type: "note", text: "Our team will coordinate the details with you. If you have any questions, reply to this email." },
      ],
    },
    {
      id: "paid-token",
      audience: "Respondent",
      name: "Token sent — cash",
      subject: "Your survey token has been sent",
      from: "Prodi-Surveys <no-reply@prodigitality.net>",
      to: "respondent",
      preheader: "Your cash token has been sent.",
      accent: "#15803D",
      vars: { firstName: "Maria", amount: "₱200", method: "GCash •••• 678", dateSent: "Jun 20, 2026" },
      blocks: [
        { type: "h", text: "Your token has been sent 💸" },
        { type: "p", text: "Thank you, {{firstName}} — your token for completing the Prodigitality baseline survey has been sent to your payout account." },
        { type: "kv", rows: [["Amount", "{{amount}}"], ["Method", "{{method}}"], ["Date sent", "{{dateSent}}"]] },
        { type: "note", text: "Please allow 1–3 business days for the amount to reflect." },
      ],
    },
    {
      id: "stakeholder",
      audience: "Stakeholder",
      name: "Weekly progress report",
      subject: "Prodi-Surveys — weekly progress report",
      from: "Prodi-Surveys <reports@prodigitality.net>",
      to: "stakeholder",
      preheader: "This week's verified counts and pipeline.",
      accent: "#1F1147",
      vars: { verifiedCount: "51 / 114", pendingQA: "11", registeredThisWeek: "+14", onTrack: "Yes" },
      blocks: [
        { type: "h", text: "Weekly progress report" },
        { type: "p", text: "Here's the latest snapshot of the baseline data collection. Full read-only dashboard available in the portal." },
        { type: "kv", rows: [["Verified to date", "{{verifiedCount}}"], ["Pending QA", "{{pendingQA}}"], ["Registered this week", "{{registeredThisWeek}}"], ["On track", "{{onTrack}}"]] },
        { type: "btn", text: "Open the dashboard" },
        { type: "note", text: "Finance and personal details are excluded from stakeholder reports." },
      ],
    },
  ];
}
